export type WritingTone = (typeof WRITING_TONES)[number];
export const WRITING_TONES = [
  "Assertive",
  "Authoritative",
  "Bold",
  "Casual",
  "Confident",
  "Conversational",
  "Emotional",
  "Formal",
  "Friendly",
  "Humorous",
  "Informative",
  "Inspirational",
  "Persuasive",
  "Professional",
  "Sarcastic",
  "Serious",
  "Simple",
  "Sincere",
  "Skeptical",
  "Sympathetic",
  "Technical",
  "Witty",
];
